name-template: "v$NEXT_MAJOR_VERSION"
tag-template: "v$NEXT_MAJOR_VERSION"
prerelease: true
exclude-labels:
  - "skip-changelog"
categories:
  - title: "❗ Breaking Changes"
    labels:
      - "breaking-change"
  - title: "🚀 Highlights"
    labels:
      - "release-highlight"
  - title: "🚀 Features"
    labels:
      - "feature"
      - "enhancement"
  - title: "🐛 Bug fixes"
    labels:
      - "bug"
  - title: "⚡ Performance improvements"
    labels:
      - "performance"
  - title: "🎨 Design"
    labels:
      - "design"
  - title: "📖 Documentation"
    labels:
      - "documentation"
  - title: "🛠 Examples"
    labels:
      - "examples"
  - title: "🌎 Accessibility"
    labels:
      - "accessibility"
  - title: "🏭 Tests"
    labels:
      - "tests"
  - title: "🧰 Misc"
    labels:
      - "build"
      - "meta"
      - "chore"
      - "CI"
  - title: "📦 Dependencies"
    labels:
      - "dependencies"
change-template: "- #$NUMBER: $TITLE"
template: |
  ## Changes
  $CHANGES
