name: Report a frontend bug
description: Tell us about a bug or issue you may have identified in Input Magic.
title: "Provide a general summary of the issue"
labels: [bug, frontend]
assignees: "@yuba-technology/frontend-team"
body:
  - type: checkboxes
    attributes:
      label: Prerequisites
      description: Take a couple minutes to help our maintainers work faster.
      options:
        - label: I have [searched](https://github.com/Yuba-Technology/Input-Magic/issues?utf8=%E2%9C%93&q=is%3Aissue) for duplicate or closed issues
          required: true
        - label: I have [validated](https://html5.validator.nu/) any HTML to avoid common problems
          required: true
        - label: I have read the [contributing guidelines](https://github.com/Yuba-Technology/Input-Magic/blob/main/.github/CONTRIBUTING.md)
          required: true
  - type: textarea
    id: what-happened
    attributes:
      label: Describe the issue
      description: Provide a summary of the issue and what you expected to happen, including specific steps to reproduce.
    validations:
      required: true
  - type: textarea
    id: reduced-test-case
    attributes:
      label: Reduced test cases
      description: Include links [reduced test case](https://css-tricks.com/reduced-test-cases/) links or suggested fixes using CodePen ([Template for reduced test cases](https://codepen.io/pen/xxxxx)).
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: What operating system(s) are you seeing the problem on?
      multiple: true
      options:
        - Windows
        - macOS
        - Android
        - iOS
        - Linux
    validations:
      required: true
  - type: dropdown
    id: browser
    attributes:
      label: What browser(s) are you seeing the problem on?
      multiple: true
      options:
        - Chrome
        - Safari
        - Firefox
        - Microsoft Edge
        - Opera
  - type: input
    id: version
    attributes:
      label: What version of Input Magic are you playing with?
      placeholder: "e.g., v5.1.0 or v4.5.2"
    validations:
      required: true
