name: Close Issue Awaiting Reply

on:
  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch:

jobs:
  issue-close-require:
    runs-on: ubuntu-latest
    steps:
      - name: awaiting reply
        uses: actions-cool/issues-helper@v3
        with:
          actions: "close-issues"
          token: ${{ secrets.BG_TOKEN }}
          issue-number: 2
          labels: "awaiting-reply"
          body: |
            As the issue was labeled with `awaiting-reply`, but there has been no response in 14 days, this issue will be closed. If you have any questions, you can comment/reply. Thank you for your contribution.
