name: Welcome new contributors
on:
  issues:
    types:
      - opened

env:
  FORCE_COLOR: 2
  NODE: 20

permissions:
  contents: read

jobs:
  greet:
    if: github.repository == 'Yuba-Technology/Input-Magic'
    runs-on: ubuntu-latest
    steps:
      - name: Create comment
        uses: actions-cool/issues-helper@a610082f8ac0cf03e357eb8dd0d5e2ba075e017e # v3.6.0
        with:
          actions: "welcome"
          token: ${{ secrets.BG_TOKEN }}
          body: |
            Hi @${{ github.event.issue.user.login }}! 👋
            Thanks for opening this issue. We will get back to you soon.
